//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Macios.Bindings.Analyzer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Macios.Bindings.Analyzer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order for the code to be generated all binding types have to be declared as partial classes..
        /// </summary>
        internal static string RBI0001Description {
            get {
                return ResourceManager.GetString("RBI0001Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The binding type &apos;{0}&apos; must be declared partial.
        /// </summary>
        internal static string RBI0001MessageFormat {
            get {
                return ResourceManager.GetString("RBI0001MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding type declaration must be partial.
        /// </summary>
        internal static string RBI0001Title {
            get {
                return ResourceManager.GetString("RBI0001Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BindingType&lt;Class&gt; can only decorate partial classes..
        /// </summary>
        internal static string RBI0002Description {
            get {
                return ResourceManager.GetString("RBI0002Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BindingType&lt;Class&gt; can only be used to decorate a class but was found on &apos;{0}&apos; which is not a class.
        /// </summary>
        internal static string RBI0002MessageFormat {
            get {
                return ResourceManager.GetString("RBI0002MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BindingType&lt;Class&gt; must be on a class.
        /// </summary>
        internal static string RBI0002Title {
            get {
                return ResourceManager.GetString("RBI0002Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BindingType&lt;Category&gt; can only decorate partial classes..
        /// </summary>
        internal static string RBI0003Description {
            get {
                return ResourceManager.GetString("RBI0003Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BindingType&lt;Category&gt; can only be used to decorate a class but was found on &apos;{0}&apos; which is not a class.
        /// </summary>
        internal static string RBI0003MessageFormat {
            get {
                return ResourceManager.GetString("RBI0003MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BindingType&lt;Category&gt; must be on a class.
        /// </summary>
        internal static string RBI0003Title {
            get {
                return ResourceManager.GetString("RBI0003Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BindingType&lt;Category&gt; can only decorate static classes..
        /// </summary>
        internal static string RBI0004Description {
            get {
                return ResourceManager.GetString("RBI0004Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BindingType&lt;Category&gt; can only be used to decorate a static class but was found on &apos;{0}&apos; which is not static.
        /// </summary>
        internal static string RBI0004MessageFormat {
            get {
                return ResourceManager.GetString("RBI0004MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BindingType&lt;Category&gt; must be on a static class.
        /// </summary>
        internal static string RBI0004Title {
            get {
                return ResourceManager.GetString("RBI0004Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BindingType&lt;Protocol&gt; can only decorate interfaces..
        /// </summary>
        internal static string RBI0005Description {
            get {
                return ResourceManager.GetString("RBI0005Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BindingType&lt;Protocol&gt; can only be used to decorate an interface but was found on &apos;{0}&apos; which is not an interface.
        /// </summary>
        internal static string RBI0005MessageFormat {
            get {
                return ResourceManager.GetString("RBI0005MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BindingType&lt;Protocol&gt; must be on an interface.
        /// </summary>
        internal static string RBI0005Title {
            get {
                return ResourceManager.GetString("RBI0005Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BindingType can only decorate enumerators..
        /// </summary>
        internal static string RBI0006Description {
            get {
                return ResourceManager.GetString("RBI0006Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BindingType can only be used to decorate an enumerator but was found on &apos;{0}&apos; which is not an enumerator.
        /// </summary>
        internal static string RBI0006MessageFormat {
            get {
                return ResourceManager.GetString("RBI0006MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BindingType must be on an enumerator.
        /// </summary>
        internal static string RBI0006Title {
            get {
                return ResourceManager.GetString("RBI0006Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BindingType&lt;StrongDictionary&gt; can only decorate classes..
        /// </summary>
        internal static string RBI0007Description {
            get {
                return ResourceManager.GetString("RBI0007Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BindingType&lt;StrongDictionary&gt; can only be used to decorate a class but was found on &apos;{0}&apos; which is not a class.
        /// </summary>
        internal static string RBI0007MessageFormat {
            get {
                return ResourceManager.GetString("RBI0007MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BindingType&lt;StrongDictionary&gt; must be on a class.
        /// </summary>
        internal static string RBI0007Title {
            get {
                return ResourceManager.GetString("RBI0007Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order for the code to be generated a smart enum value has to have a backing field..
        /// </summary>
        internal static string RBI0008Description {
            get {
                return ResourceManager.GetString("RBI0008Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The enum value &apos;{0}&apos; must be tagged with a Field&lt;EnumValue&gt; attribute.
        /// </summary>
        internal static string RBI0008MessageFormat {
            get {
                return ResourceManager.GetString("RBI0008MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart enum values must be tagged with an Field&lt;EnumValue&gt; attribute.
        /// </summary>
        internal static string RBI0008Title {
            get {
                return ResourceManager.GetString("RBI0008Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart enum backing field cannot appear more than once..
        /// </summary>
        internal static string RBI0009Description {
            get {
                return ResourceManager.GetString("RBI0009Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The backing field &apos;{0}&apos; for the enum value &apos;{1}&apos; is already in use for the enum value &apos;{2}&apos;.
        /// </summary>
        internal static string RBI0009MessageFormat {
            get {
                return ResourceManager.GetString("RBI0009MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart enum backing field cannot appear more than once.
        /// </summary>
        internal static string RBI0009Title {
            get {
                return ResourceManager.GetString("RBI0009Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart enum backing field must be a valid identifier..
        /// </summary>
        internal static string RBI0010Description {
            get {
                return ResourceManager.GetString("RBI0010Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The enum value &apos;{0}&apos; backing field &apos;{1}&apos; is not a valid identifier.
        /// </summary>
        internal static string RBI0010MessageFormat {
            get {
                return ResourceManager.GetString("RBI0010MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart enum backing field must represent a valid C# identifier to be used.
        /// </summary>
        internal static string RBI0010Title {
            get {
                return ResourceManager.GetString("RBI0010Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart enum backing field for a non Apple framework must provide a library name..
        /// </summary>
        internal static string RBI0011Description {
            get {
                return ResourceManager.GetString("RBI0011Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field attribute for the enum value &apos;{0}&apos; must set the property &apos;LibraryName&apos;.
        /// </summary>
        internal static string RBI0011MessageFormat {
            get {
                return ResourceManager.GetString("RBI0011MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non Apple framework bindings must provide a library name.
        /// </summary>
        internal static string RBI0011Title {
            get {
                return ResourceManager.GetString("RBI0011Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields of known Apple frameworks should not provide a LibraryName..
        /// </summary>
        internal static string RBI0012Description {
            get {
                return ResourceManager.GetString("RBI0012Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Field attribute for the enum value &apos;{0}&apos; must not provide a value for &apos;LibraryName&apos;.
        /// </summary>
        internal static string RBI0012MessageFormat {
            get {
                return ResourceManager.GetString("RBI0012MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not provide the LibraryName for known Apple frameworks.
        /// </summary>
        internal static string RBI0012Title {
            get {
                return ResourceManager.GetString("RBI0012Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong flags were used in the FieldAttribute when applying it on an enum value..
        /// </summary>
        internal static string RBI0013Description {
            get {
                return ResourceManager.GetString("RBI0013Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used attribute &apos;{0}&apos; on enum value &apos;{1}&apos; when &apos;ObjCBindings.FieldAttribute&lt;ObjCBindings.EnumValue&gt;&apos; was expected.
        /// </summary>
        internal static string RBI0013MessageFormat {
            get {
                return ResourceManager.GetString("RBI0013MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum values must be tagged with Field&lt;EnumValue&gt;.
        /// </summary>
        internal static string RBI0013Title {
            get {
                return ResourceManager.GetString("RBI0013Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Native object accessed by handle must be kept alive, either implicitly by access or through GC.KeepAlive..
        /// </summary>
        internal static string RBI0014Description {
            get {
                return ResourceManager.GetString("RBI0014Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable &apos;{0}&apos; has its Handle property accessed but is not kept alive later in the method.
        /// </summary>
        internal static string RBI0014MessageFormat {
            get {
                return ResourceManager.GetString("RBI0014MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INativeObject not kept alive after Handle access.
        /// </summary>
        internal static string RBI0014Title {
            get {
                return ResourceManager.GetString("RBI0014Title", resourceCulture);
            }
        }
    }
}
