using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using NUnit.Framework;
using Mono.Cecil;
using Mono.Cecil.Cil;

using ObjCRuntime;

using Xamarin.Tests;
using Xamarin.Utils;

#nullable enable

namespace Cecil.Tests {
	public partial class ApiAvailabilityTest {
		static HashSet<string> knownFailuresAvailabilityWarnings = new HashSet<string> {
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoder.GpuRegistryId' is supported on: 'ios' 13.0 and later, 'tvos' 13.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoder.IncludeStandardDefinitionDVEncoders' is supported on: 'ios' 15.0 and later, 'tvos' 15.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoder.InstanceLimit' is supported on: 'ios' 13.0 and later, 'tvos' 13.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoder.IsHardwareAccelerated' is supported on: 'ios' 13.0 and later, 'tvos' 13.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoder.PerformanceRating' is supported on: 'ios' 13.0 and later, 'tvos' 13.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoder.QualityRating' is supported on: 'ios' 13.0 and later, 'tvos' 13.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoder.SupportedSelectionProperties' is supported on: 'ios' 13.0 and later, 'tvos' 13.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoder.SupportsFrameReordering' is supported on: 'ios' 14.2 and later, 'tvos' 14.2 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoderList.GpuRegistryId.get' is supported on: 'ios' 13.0 and later, 'tvos' 13.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoderList.GpuRegistryId' is supported on: 'ios' 13.0 and later, 'tvos' 13.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoderList.IncludeStandardDefinitionDVEncoders.get' is supported on: 'ios' 15.0 and later, 'tvos' 15.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoderList.IncludeStandardDefinitionDVEncoders' is supported on: 'ios' 15.0 and later, 'tvos' 15.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoderList.InstanceLimit.get' is supported on: 'ios' 13.0 and later, 'tvos' 13.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoderList.InstanceLimit' is supported on: 'ios' 13.0 and later, 'tvos' 13.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoderList.IsHardwareAccelerated.get' is supported on: 'ios' 13.0 and later, 'tvos' 13.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoderList.IsHardwareAccelerated' is supported on: 'ios' 13.0 and later, 'tvos' 13.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoderList.PerformanceRating.get' is supported on: 'ios' 13.0 and later, 'tvos' 13.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoderList.PerformanceRating' is supported on: 'ios' 13.0 and later, 'tvos' 13.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoderList.QualityRating.get' is supported on: 'ios' 13.0 and later, 'tvos' 13.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoderList.QualityRating' is supported on: 'ios' 13.0 and later, 'tvos' 13.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoderList.SupportedSelectionProperties.get' is supported on: 'ios' 13.0 and later, 'tvos' 13.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoderList.SupportedSelectionProperties' is supported on: 'ios' 13.0 and later, 'tvos' 13.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoderList.SupportsFrameReordering.get' is supported on: 'ios' 14.2 and later, 'tvos' 14.2 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoderList.SupportsFrameReordering' is supported on: 'ios' 14.2 and later, 'tvos' 14.2 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
		};
	}
}
