using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using NUnit.Framework;
using Mono.Cecil;
using Mono.Cecil.Cil;

using ObjCRuntime;

using Xamarin.Tests;
using Xamarin.Utils;

#nullable enable

namespace Cecil.Tests {
	public partial class ApiAvailabilityTest {
		static HashSet<string> knownFailuresAvailabilityWarnings = new HashSet<string> {
			"/src/Foundation/NSAttributedString.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'NSAttributedString._InitWithContentsOfMarkdownFile(NSUrl, NSAttributedStringMarkdownParsingOptions?, NSUrl?, out NSError?)' is supported on: 'ios' 15.0 and later, 'tvos' 15.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/Foundation/NSAttributedString.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'NSAttributedString._InitWithMarkdown(NSData, NSAttributedStringMarkdownParsingOptions?, NSUrl?, out NSError?)' is supported on: 'ios' 15.0 and later, 'tvos' 15.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/Foundation/NSAttributedString.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'NSAttributedString._InitWithMarkdownString(string, NSAttributedStringMarkdownParsingOptions?, NSUrl?, out NSError?)' is supported on: 'ios' 15.0 and later, 'tvos' 15.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/Foundation/NSAttributedStringDocumentAttributes.cs has 2 occurrences of This call site is reachable on: 'ios' 13.0 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later. 'NSAttributedStringDocumentReadingOptionKey.ReadAccessUrlDocumentOption.get' is supported on: 'macOS/OSX'. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/Foundation/NSAttributedStringDocumentAttributes.cs has 4 occurrences of This call site is reachable on: 'ios' 13.0 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later. 'NSAttributedStringDocumentReadingOptionKey.ReadAccessUrlDocumentOption.get' is supported on: 'ios' 13.0 and later, 'maccatalyst'. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/Foundation/NSAttributedStringDocumentAttributes.cs has 4 occurrences of This call site is reachable on: 'ios' 13.0 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later. 'NSAttributedStringDocumentReadingOptionKey.ReadAccessUrlDocumentOption' is supported on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/Foundation/NSDictionary_2.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'NSDictionary' is obsoleted on: 'ios' 13.0 and later (Use 'NSMutableDictionary(NSUrl)' constructor instead.), 'maccatalyst' 13.0 and later (Use 'NSMutableDictionary(NSUrl)' constructor instead.), 'macOS/OSX' 10.15 and later (Use 'NSMutableDictionary(NSUrl)' constructor instead.), 'tvos' 13.0 and later (Use 'NSMutableDictionary(NSUrl)' constructor instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422)",
			"/src/Foundation/NSDictionary_2.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'NSDictionary' is obsoleted on: 'ios' 13.0 and later (Use 'NSMutableDictionary(string)' constructor instead.), 'maccatalyst' 13.0 and later (Use 'NSMutableDictionary(string)' constructor instead.), 'macOS/OSX' 10.15 and later (Use 'NSMutableDictionary(string)' constructor instead.), 'tvos' 13.0 and later (Use 'NSMutableDictionary(string)' constructor instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422)",
			"/src/Foundation/NSStream.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'CFHost.Create(IPEndPoint)' is obsoleted on: 'ios' 15.0 and later (Use 'Network.framework' instead.), 'maccatalyst' 15.0 and later (Use 'Network.framework' instead.), 'macOS/OSX' 12.0 and later (Use 'Network.framework' instead.), 'tvos' 15.0 and later (Use 'Network.framework' instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422)",
			"/src/Foundation/NSStream.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'CFStream.CFStreamCreatePairWithPeerSocketSignature(nint, CFSocketSignature*, nint*, nint*)' is obsoleted on: 'ios' 15.0 and later (Use 'Network.framework' instead.), 'maccatalyst' 15.0 and later (Use 'Network.framework' instead.), 'macOS/OSX' 12.0 and later (Use 'Network.framework' instead.), 'tvos' 15.0 and later (Use 'Network.framework' instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422)",
			"/src/Foundation/NSStream.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'CFStream.CFStreamCreatePairWithSocket(nint, CFSocketNativeHandle, nint*, nint*)' is obsoleted on: 'ios' 15.0 and later (Use 'Network.framework' instead.), 'maccatalyst' 15.0 and later (Use 'Network.framework' instead.), 'macOS/OSX' 12.0 and later (Use 'Network.framework' instead.), 'tvos' 15.0 and later (Use 'Network.framework' instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422)",
			"/src/Foundation/NSStream.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'CFStream.CFStreamCreatePairWithSocketToCFHost(nint, nint, int, nint*, nint*)' is obsoleted on: 'ios' 15.0 and later (Use 'Network.framework' instead.), 'maccatalyst' 15.0 and later (Use 'Network.framework' instead.), 'macOS/OSX' 12.0 and later (Use 'Network.framework' instead.), 'tvos' 15.0 and later (Use 'Network.framework' instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422)",
			"/src/Foundation/NSUrlSessionHandler.cs has 12 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'NSUrlSessionHandler.ClientCertificateOptions' is unsupported on: 'ios' all versions, 'maccatalyst' all versions, 'macOS/OSX' all versions, 'tvos' all versions. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/Foundation/NSUrlSessionHandler.cs has 20 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'NSUrlSessionConfiguration.TLSMinimumSupportedProtocol' is obsoleted on: 'ios' 13.0 and later (Use 'TlsMinimumSupportedProtocolVersion' instead.), 'maccatalyst' 13.0 and later (Use 'TlsMinimumSupportedProtocolVersion' instead.), 'macOS/OSX' 10.15 and later (Use 'TlsMinimumSupportedProtocolVersion' instead.), 'tvos' 13.0 and later (Use 'TlsMinimumSupportedProtocolVersion' instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422)",
			"/src/Foundation/NSUrlSessionHandler.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'SecTrust.GetCertificateChain()' is supported on: 'ios' 15.0 and later, 'tvos' 15.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/Foundation/NSUrlSessionHandler.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'SecTrust.this[nint]' is obsoleted on: 'ios' 15.0 and later (Use the 'GetCertificateChain' method instead.), 'maccatalyst' all versions, 'macOS/OSX' all versions, 'tvos' 15.0 and later (Use the 'GetCertificateChain' method instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422)",
			"/src/Foundation/NSUrlSessionHandler.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'SslProtocol.Ssl_3_0' is obsoleted on: 'ios' 13.0 and later (Use 'TlsProtocolVersion' instead.), 'maccatalyst' 13.0 and later (Use 'TlsProtocolVersion' instead.), 'macOS/OSX' 10.15 and later (Use 'TlsProtocolVersion' instead.), 'tvos' 13.0 and later (Use 'TlsProtocolVersion' instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422)",
			"/src/Foundation/NSUrlSessionHandler.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'SslProtocol.Tls_1_0' is obsoleted on: 'ios' 13.0 and later (Use 'TlsProtocolVersion' instead.), 'maccatalyst' 13.0 and later (Use 'TlsProtocolVersion' instead.), 'macOS/OSX' 10.15 and later (Use 'TlsProtocolVersion' instead.), 'tvos' 13.0 and later (Use 'TlsProtocolVersion' instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422)",
			"/src/Foundation/NSUrlSessionHandler.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'SslProtocol.Tls_1_1' is obsoleted on: 'ios' 13.0 and later (Use 'TlsProtocolVersion' instead.), 'maccatalyst' 13.0 and later (Use 'TlsProtocolVersion' instead.), 'macOS/OSX' 10.15 and later (Use 'TlsProtocolVersion' instead.), 'tvos' 13.0 and later (Use 'TlsProtocolVersion' instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422)",
			"/src/Foundation/NSUrlSessionHandler.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'SslProtocol.Tls_1_2' is obsoleted on: 'ios' 13.0 and later (Use 'TlsProtocolVersion' instead.), 'maccatalyst' 13.0 and later (Use 'TlsProtocolVersion' instead.), 'macOS/OSX' 10.15 and later (Use 'TlsProtocolVersion' instead.), 'tvos' 13.0 and later (Use 'TlsProtocolVersion' instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422)",
			"/src/Foundation/NSUrlSessionHandler.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'SslProtocol.Tls_1_3' is obsoleted on: 'ios' 13.0 and later (Use 'TlsProtocolVersion' instead.), 'maccatalyst' 13.0 and later (Use 'TlsProtocolVersion' instead.), 'macOS/OSX' 10.15 and later (Use 'TlsProtocolVersion' instead.), 'tvos' 13.0 and later (Use 'TlsProtocolVersion' instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422)",
			"/src/GameController/GCExtendedGamepadSnapshot.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'GCExtendedGamepadSnapShotDataV100' is obsoleted on: 'ios' 12.2 and later (Use 'GCExtendedGamepadSnapshotData' instead.), 'maccatalyst' 12.2 and later (Use 'GCExtendedGamepadSnapshotData' instead.), 'macOS/OSX' 10.14.4 and later (Use 'GCExtendedGamepadSnapshotData' instead.), 'tvos' 12.2 and later (Use 'GCExtendedGamepadSnapshotData' instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422)",
			"/src/System.Net.Http/CFNetworkHandler.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'CFHTTPStream.GetResponseHeader()' is obsoleted on: 'ios' 9.0 and later (Use 'NSUrlSession'.), 'maccatalyst' 9.0 and later (Use 'NSUrlSession'.), 'macOS/OSX' 10.11 and later (Use 'NSUrlSession'.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422)",
			"/src/System.Net.Http/CFNetworkHandler.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'CFHTTPStream.SetProxy(CFProxySettings)' is obsoleted on: 'ios' 9.0 and later (Use 'NSUrlSession'.), 'maccatalyst' 9.0 and later (Use 'NSUrlSession'.), 'macOS/OSX' 10.11 and later (Use 'NSUrlSession'.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422)",
			"/src/System.Net.Http/CFNetworkHandler.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'CFHTTPStream.ShouldAutoredirect' is obsoleted on: 'ios' 9.0 and later (Use 'NSUrlSession'.), 'maccatalyst' 9.0 and later (Use 'NSUrlSession'.), 'macOS/OSX' 10.11 and later (Use 'NSUrlSession'.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422)",
			"/src/System.Net.Http/CFNetworkHandler.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'CFStream.CreateForHTTPRequest(CFHTTPMessage)' is obsoleted on: 'ios' 9.0 and later (Use 'NSUrlSession' instead.), 'maccatalyst' 9.0 and later (Use 'NSUrlSession' instead.), 'macOS/OSX' 10.11 and later (Use 'NSUrlSession' instead.), 'tvos' 9.0 and later (Use 'NSUrlSession' instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422)",
			"/src/SystemConfiguration/NetworkReachability.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'NetworkReachability.GetFlags(out NetworkReachabilityFlags)' is obsoleted on: 'ios' 17.4 and later (Use 'NSUrlSession' or 'NWConnection' instead.), 'maccatalyst' 17.4 and later (Use 'NSUrlSession' or 'NWConnection' instead.), 'macOS/OSX' 14.4 and later (Use 'NSUrlSession' or 'NWConnection' instead.), 'tvos' 17.4 and later (Use 'NSUrlSession' or 'NWConnection' instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422)",
			"/src/SystemConfiguration/NetworkReachability.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'NetworkReachability.Schedule(CFRunLoop, string)' is obsoleted on: 'ios' 17.4 and later (Use 'NSUrlSession' or 'NWConnection' instead.), 'maccatalyst' 17.4 and later (Use 'NSUrlSession' or 'NWConnection' instead.), 'macOS/OSX' 14.4 and later (Use 'NSUrlSession' or 'NWConnection' instead.), 'tvos' 17.4 and later (Use 'NSUrlSession' or 'NWConnection' instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422)",
			"/src/SystemConfiguration/NetworkReachability.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'NetworkReachability.SCNetworkReachabilityCreateWithAddress(nint, NetworkReachability.sockaddr_in*)' is obsoleted on: 'ios' 17.4 and later (Use 'NSUrlSession' or 'NWConnection' instead.), 'maccatalyst' 17.4 and later (Use 'NSUrlSession' or 'NWConnection' instead.), 'macOS/OSX' 14.4 and later (Use 'NSUrlSession' or 'NWConnection' instead.), 'tvos' 17.4 and later (Use 'NSUrlSession' or 'NWConnection' instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422)",
			"/src/SystemConfiguration/NetworkReachability.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'NetworkReachability.SCNetworkReachabilityCreateWithAddressPair(nint, NetworkReachability.sockaddr_in*, NetworkReachability.sockaddr_in*)' is obsoleted on: 'ios' 17.4 and later (Use 'NSUrlSession' or 'NWConnection' instead.), 'maccatalyst' 17.4 and later (Use 'NSUrlSession' or 'NWConnection' instead.), 'macOS/OSX' 14.4 and later (Use 'NSUrlSession' or 'NWConnection' instead.), 'tvos' 17.4 and later (Use 'NSUrlSession' or 'NWConnection' instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422)",
			"/src/SystemConfiguration/NetworkReachability.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'NetworkReachability.SCNetworkReachabilityCreateWithAddressPair(nint, NetworkReachability.sockaddr_in*, nint)' is obsoleted on: 'ios' 17.4 and later (Use 'NSUrlSession' or 'NWConnection' instead.), 'maccatalyst' 17.4 and later (Use 'NSUrlSession' or 'NWConnection' instead.), 'macOS/OSX' 14.4 and later (Use 'NSUrlSession' or 'NWConnection' instead.), 'tvos' 17.4 and later (Use 'NSUrlSession' or 'NWConnection' instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422)",
			"/src/SystemConfiguration/NetworkReachability.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'NetworkReachability.SCNetworkReachabilityCreateWithAddressPair(nint, nint, NetworkReachability.sockaddr_in*)' is obsoleted on: 'ios' 17.4 and later (Use 'NSUrlSession' or 'NWConnection' instead.), 'maccatalyst' 17.4 and later (Use 'NSUrlSession' or 'NWConnection' instead.), 'macOS/OSX' 14.4 and later (Use 'NSUrlSession' or 'NWConnection' instead.), 'tvos' 17.4 and later (Use 'NSUrlSession' or 'NWConnection' instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422)",
			"/src/SystemConfiguration/NetworkReachability.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'NetworkReachability.SCNetworkReachabilityCreateWithName(nint, nint)' is obsoleted on: 'ios' 17.4 and later (Use 'NSUrlSession' or 'NWConnection' instead.), 'maccatalyst' 17.4 and later (Use 'NSUrlSession' or 'NWConnection' instead.), 'macOS/OSX' 14.4 and later (Use 'NSUrlSession' or 'NWConnection' instead.), 'tvos' 17.4 and later (Use 'NSUrlSession' or 'NWConnection' instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422)",
			"/src/SystemConfiguration/NetworkReachability.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'NetworkReachability.Unschedule(CFRunLoop, string)' is obsoleted on: 'ios' 17.4 and later (Use 'NSUrlSession' or 'NWConnection' instead.), 'maccatalyst' 17.4 and later (Use 'NSUrlSession' or 'NWConnection' instead.), 'macOS/OSX' 14.4 and later (Use 'NSUrlSession' or 'NWConnection' instead.), 'tvos' 17.4 and later (Use 'NSUrlSession' or 'NWConnection' instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422)",
			"/src/UIKit/UICellAccessory.cs has 6 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'UICellAccessory' is supported on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'tvos' 12.2 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/UIKit/UIDevice.cs has 2 occurrences of This call site is reachable on all platforms. 'UIDevice.SystemVersion' is supported on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/UIKit/UIFontFeature.cs has 6 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'FontFeatureGroup.LetterCase' is obsoleted on: 'ios' 6.0 and later, 'maccatalyst' all versions, 'macOS/OSX' 10.7 and later, 'tvos' all versions. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422)",
			"/src/UIKit/UIImage.cs has 3 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'UIGraphics.BeginImageContext(CGSize)' is unsupported on: 'ios' 17.0 and later, 'maccatalyst' 17.0 and later, 'tvos' 17.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/UIKit/UIImage.cs has 3 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'UIGraphics.BeginImageContextWithOptions(CGSize, bool, NFloat)' is unsupported on: 'ios' 17.0 and later, 'maccatalyst' 17.0 and later, 'tvos' 17.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/UIKit/UIImage.cs has 6 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'UIGraphics.EndImageContext()' is unsupported on: 'ios' 17.0 and later, 'maccatalyst' 17.0 and later, 'tvos' 17.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/UIKit/UIImage.cs has 6 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'UIGraphics.GetImageFromCurrentImageContext()' is unsupported on: 'ios' 17.0 and later, 'maccatalyst' 17.0 and later, 'tvos' 17.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/UIKit/UIImagePickerController.cs has 2 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'UIImagePickerController.ReferenceUrl.get' is obsoleted on: 'ios' 11.0 and later (Use 'UIImagePickerController.PHAsset' instead.), 'maccatalyst' 11.0 and later (Use 'UIImagePickerController.PHAsset' instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422)",
			"/src/UIKit/UIImagePickerController.cs has 2 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'UIImagePickerController.ReferenceUrl.get' is supported on: 'ios', 'maccatalyst'. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/UIKit/UIImagePickerController.cs has 2 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'UIImagePickerController.ReferenceUrl' is obsoleted on: 'ios' 11.0 and later (Use 'UIImagePickerController.PHAsset' instead.), 'maccatalyst' 11.0 and later (Use 'UIImagePickerController.PHAsset' instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422)",
			"/src/UIKit/UIViewControllerTransitionCoordinatorContext.cs has 3 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'UITransitionContext.FromViewKey.get' is supported on: 'ios', 'maccatalyst', 'tvos'. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/UIKit/UIViewControllerTransitionCoordinatorContext.cs has 3 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'UITransitionContext.ToViewKey.get' is supported on: 'ios', 'maccatalyst', 'tvos'. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/UIKit/UIWindowScene.cs has 3 occurrences of This call site is reachable on: 'ios' 13.0 and later, 'maccatalyst' 12.2 and later, 'tvos' 13.0 and later. 'IUITraitChangeObservable._RegisterForTraitChanges(IUITraitChangeObservable, Action<IUITraitEnvironment, UITraitCollection>, params Type[])' is supported on: 'ios' 17.0 and later, 'maccatalyst' 17.0 and later, 'tvos' 17.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/UIKit/UIWindowScene.cs has 3 occurrences of This call site is reachable on: 'ios' 13.0 and later, 'maccatalyst' 12.2 and later, 'tvos' 13.0 and later. 'IUITraitChangeObservable._RegisterForTraitChanges(IUITraitChangeObservable, Type[], Action<IUITraitEnvironment, UITraitCollection>)' is supported on: 'ios' 17.0 and later, 'maccatalyst' 17.0 and later, 'tvos' 17.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/UIKit/UIWindowScene.cs has 3 occurrences of This call site is reachable on: 'ios' 13.0 and later, 'maccatalyst' 12.2 and later, 'tvos' 13.0 and later. 'IUITraitChangeObservable._RegisterForTraitChanges(IUITraitChangeObservable, Type[], NSObject, Selector)' is supported on: 'ios' 17.0 and later, 'maccatalyst' 17.0 and later, 'tvos' 17.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/UIKit/UIWindowScene.cs has 3 occurrences of This call site is reachable on: 'ios' 13.0 and later, 'maccatalyst' 12.2 and later, 'tvos' 13.0 and later. 'IUITraitChangeObservable._RegisterForTraitChanges(IUITraitChangeObservable, Type[], Selector)' is supported on: 'ios' 17.0 and later, 'maccatalyst' 17.0 and later, 'tvos' 17.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/UIKit/UIWindowScene.cs has 3 occurrences of This call site is reachable on: 'ios' 13.0 and later, 'maccatalyst' 12.2 and later, 'tvos' 13.0 and later. 'IUITraitChangeObservable._RegisterForTraitChanges<T>(IUITraitChangeObservable, Action<IUITraitEnvironment, UITraitCollection>)' is supported on: 'ios' 17.0 and later, 'maccatalyst' 17.0 and later, 'tvos' 17.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/UIKit/UIWindowScene.cs has 3 occurrences of This call site is reachable on: 'ios' 13.0 and later, 'maccatalyst' 12.2 and later, 'tvos' 13.0 and later. 'IUITraitChangeObservable._RegisterForTraitChanges<T1, T2, T3, T4>(IUITraitChangeObservable, Action<IUITraitEnvironment, UITraitCollection>)' is supported on: 'ios' 17.0 and later, 'maccatalyst' 17.0 and later, 'tvos' 17.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/UIKit/UIWindowScene.cs has 3 occurrences of This call site is reachable on: 'ios' 13.0 and later, 'maccatalyst' 12.2 and later, 'tvos' 13.0 and later. 'IUITraitChangeObservable._RegisterForTraitChanges<T1, T2, T3>(IUITraitChangeObservable, Action<IUITraitEnvironment, UITraitCollection>)' is supported on: 'ios' 17.0 and later, 'maccatalyst' 17.0 and later, 'tvos' 17.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/UIKit/UIWindowScene.cs has 3 occurrences of This call site is reachable on: 'ios' 13.0 and later, 'maccatalyst' 12.2 and later, 'tvos' 13.0 and later. 'IUITraitChangeObservable._RegisterForTraitChanges<T1, T2>(IUITraitChangeObservable, Action<IUITraitEnvironment, UITraitCollection>)' is supported on: 'ios' 17.0 and later, 'maccatalyst' 17.0 and later, 'tvos' 17.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoder.GpuRegistryId' is supported on: 'ios' 13.0 and later, 'tvos' 13.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoder.IncludeStandardDefinitionDVEncoders' is supported on: 'ios' 15.0 and later, 'tvos' 15.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoder.InstanceLimit' is supported on: 'ios' 13.0 and later, 'tvos' 13.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoder.IsHardwareAccelerated' is supported on: 'ios' 13.0 and later, 'tvos' 13.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoder.PerformanceRating' is supported on: 'ios' 13.0 and later, 'tvos' 13.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoder.QualityRating' is supported on: 'ios' 13.0 and later, 'tvos' 13.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoder.SupportedSelectionProperties' is supported on: 'ios' 13.0 and later, 'tvos' 13.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoder.SupportsFrameReordering' is supported on: 'ios' 14.2 and later, 'tvos' 14.2 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoderList.GpuRegistryId.get' is supported on: 'ios' 13.0 and later, 'tvos' 13.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoderList.GpuRegistryId' is supported on: 'ios' 13.0 and later, 'tvos' 13.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoderList.IncludeStandardDefinitionDVEncoders.get' is supported on: 'ios' 15.0 and later, 'tvos' 15.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoderList.IncludeStandardDefinitionDVEncoders' is supported on: 'ios' 15.0 and later, 'tvos' 15.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoderList.InstanceLimit.get' is supported on: 'ios' 13.0 and later, 'tvos' 13.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoderList.InstanceLimit' is supported on: 'ios' 13.0 and later, 'tvos' 13.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoderList.IsHardwareAccelerated.get' is supported on: 'ios' 13.0 and later, 'tvos' 13.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoderList.IsHardwareAccelerated' is supported on: 'ios' 13.0 and later, 'tvos' 13.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoderList.PerformanceRating.get' is supported on: 'ios' 13.0 and later, 'tvos' 13.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoderList.PerformanceRating' is supported on: 'ios' 13.0 and later, 'tvos' 13.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoderList.QualityRating.get' is supported on: 'ios' 13.0 and later, 'tvos' 13.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoderList.QualityRating' is supported on: 'ios' 13.0 and later, 'tvos' 13.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoderList.SupportedSelectionProperties.get' is supported on: 'ios' 13.0 and later, 'tvos' 13.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoderList.SupportedSelectionProperties' is supported on: 'ios' 13.0 and later, 'tvos' 13.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoderList.SupportsFrameReordering.get' is supported on: 'ios' 14.2 and later, 'tvos' 14.2 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoderList.SupportsFrameReordering' is supported on: 'ios' 14.2 and later, 'tvos' 14.2 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/WebKit/WebNavigationPolicyEventArgs.cs has 1 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'WebPolicyDelegate.WebActionButtonKey' is obsoleted on: 'macOS/OSX' 10.14 and later (No longer supported.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422)",
			"/src/WebKit/WebNavigationPolicyEventArgs.cs has 1 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'WebPolicyDelegate.WebActionElementKey' is obsoleted on: 'macOS/OSX' 10.14 and later (No longer supported.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422)",
			"/src/WebKit/WebNavigationPolicyEventArgs.cs has 1 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'WebPolicyDelegate.WebActionModifierFlagsKey' is obsoleted on: 'macOS/OSX' 10.14 and later (No longer supported.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422)",
			"/src/WebKit/WebNavigationPolicyEventArgs.cs has 1 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'WebPolicyDelegate.WebActionNavigationTypeKey' is obsoleted on: 'macOS/OSX' 10.14 and later (No longer supported.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422)",
			"/src/WebKit/WebNavigationPolicyEventArgs.cs has 1 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'WebPolicyDelegate.WebActionOriginalUrlKey' is obsoleted on: 'macOS/OSX' 10.14 and later (No longer supported.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422)",
		};
	}
}
