using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using NUnit.Framework;
using Mono.Cecil;
using Mono.Cecil.Cil;

using ObjCRuntime;

using Xamarin.Tests;
using Xamarin.Utils;

#nullable enable

namespace Cecil.Tests {
	public partial class ApiAvailabilityTest {
		static HashSet<string> knownFailuresAvailabilityWarnings = new HashSet<string> {
			"/src/Foundation/NSAttributedString.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'NSAttributedString._InitWithContentsOfMarkdownFile(NSUrl, NSAttributedStringMarkdownParsingOptions?, NSUrl?, out NSError?)' is supported on: 'ios' 15.0 and later, 'tvos' 15.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/Foundation/NSAttributedString.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'NSAttributedString._InitWithMarkdown(NSData, NSAttributedStringMarkdownParsingOptions?, NSUrl?, out NSError?)' is supported on: 'ios' 15.0 and later, 'tvos' 15.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/Foundation/NSAttributedString.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'NSAttributedString._InitWithMarkdownString(string, NSAttributedStringMarkdownParsingOptions?, NSUrl?, out NSError?)' is supported on: 'ios' 15.0 and later, 'tvos' 15.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/Foundation/NSAttributedStringDocumentAttributes.cs has 2 occurrences of This call site is reachable on: 'ios' 13.0 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later. 'NSAttributedStringDocumentReadingOptionKey.ReadAccessUrlDocumentOption.get' is supported on: 'macOS/OSX'. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/Foundation/NSAttributedStringDocumentAttributes.cs has 4 occurrences of This call site is reachable on: 'ios' 13.0 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later. 'NSAttributedStringDocumentReadingOptionKey.ReadAccessUrlDocumentOption.get' is supported on: 'ios' 13.0 and later, 'maccatalyst'. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/Foundation/NSAttributedStringDocumentAttributes.cs has 4 occurrences of This call site is reachable on: 'ios' 13.0 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later. 'NSAttributedStringDocumentReadingOptionKey.ReadAccessUrlDocumentOption' is supported on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/Foundation/NSDictionary_2.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'NSDictionary' is obsoleted on: 'ios' 13.0 and later (Use 'NSMutableDictionary(NSUrl)' constructor instead.), 'maccatalyst' 13.0 and later (Use 'NSMutableDictionary(NSUrl)' constructor instead.), 'macOS/OSX' 10.15 and later (Use 'NSMutableDictionary(NSUrl)' constructor instead.), 'tvos' 13.0 and later (Use 'NSMutableDictionary(NSUrl)' constructor instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422)",
			"/src/Foundation/NSDictionary_2.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'NSDictionary' is obsoleted on: 'ios' 13.0 and later (Use 'NSMutableDictionary(string)' constructor instead.), 'maccatalyst' 13.0 and later (Use 'NSMutableDictionary(string)' constructor instead.), 'macOS/OSX' 10.15 and later (Use 'NSMutableDictionary(string)' constructor instead.), 'tvos' 13.0 and later (Use 'NSMutableDictionary(string)' constructor instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422)",
			"/src/Foundation/NSStream.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'CFHost.Create(IPEndPoint)' is obsoleted on: 'ios' 15.0 and later (Use 'Network.framework' instead.), 'maccatalyst' 15.0 and later (Use 'Network.framework' instead.), 'macOS/OSX' 12.0 and later (Use 'Network.framework' instead.), 'tvos' 15.0 and later (Use 'Network.framework' instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422)",
			"/src/Foundation/NSStream.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'CFStream.CFStreamCreatePairWithPeerSocketSignature(nint, CFSocketSignature*, nint*, nint*)' is obsoleted on: 'ios' 15.0 and later (Use 'Network.framework' instead.), 'maccatalyst' 15.0 and later (Use 'Network.framework' instead.), 'macOS/OSX' 12.0 and later (Use 'Network.framework' instead.), 'tvos' 15.0 and later (Use 'Network.framework' instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422)",
			"/src/Foundation/NSStream.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'CFStream.CFStreamCreatePairWithSocket(nint, CFSocketNativeHandle, nint*, nint*)' is obsoleted on: 'ios' 15.0 and later (Use 'Network.framework' instead.), 'maccatalyst' 15.0 and later (Use 'Network.framework' instead.), 'macOS/OSX' 12.0 and later (Use 'Network.framework' instead.), 'tvos' 15.0 and later (Use 'Network.framework' instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422)",
			"/src/Foundation/NSStream.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'CFStream.CFStreamCreatePairWithSocketToCFHost(nint, nint, int, nint*, nint*)' is obsoleted on: 'ios' 15.0 and later (Use 'Network.framework' instead.), 'maccatalyst' 15.0 and later (Use 'Network.framework' instead.), 'macOS/OSX' 12.0 and later (Use 'Network.framework' instead.), 'tvos' 15.0 and later (Use 'Network.framework' instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422)",
			"/src/Foundation/NSUrlSessionHandler.cs has 20 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'NSUrlSessionConfiguration.TLSMinimumSupportedProtocol' is obsoleted on: 'ios' 13.0 and later (Use 'TlsMinimumSupportedProtocolVersion' instead.), 'maccatalyst' 13.0 and later (Use 'TlsMinimumSupportedProtocolVersion' instead.), 'macOS/OSX' 10.15 and later (Use 'TlsMinimumSupportedProtocolVersion' instead.), 'tvos' 13.0 and later (Use 'TlsMinimumSupportedProtocolVersion' instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422)",
			"/src/Foundation/NSUrlSessionHandler.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'SecTrust.GetCertificateChain()' is supported on: 'ios' 15.0 and later, 'tvos' 15.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/Foundation/NSUrlSessionHandler.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'SecTrust.this[nint]' is obsoleted on: 'ios' 15.0 and later (Use the 'GetCertificateChain' method instead.), 'maccatalyst' all versions, 'macOS/OSX' all versions, 'tvos' 15.0 and later (Use the 'GetCertificateChain' method instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422)",
			"/src/Foundation/NSUrlSessionHandler.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'SslProtocol.Ssl_3_0' is obsoleted on: 'ios' 13.0 and later (Use 'TlsProtocolVersion' instead.), 'maccatalyst' 13.0 and later (Use 'TlsProtocolVersion' instead.), 'macOS/OSX' 10.15 and later (Use 'TlsProtocolVersion' instead.), 'tvos' 13.0 and later (Use 'TlsProtocolVersion' instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422)",
			"/src/Foundation/NSUrlSessionHandler.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'SslProtocol.Tls_1_0' is obsoleted on: 'ios' 13.0 and later (Use 'TlsProtocolVersion' instead.), 'maccatalyst' 13.0 and later (Use 'TlsProtocolVersion' instead.), 'macOS/OSX' 10.15 and later (Use 'TlsProtocolVersion' instead.), 'tvos' 13.0 and later (Use 'TlsProtocolVersion' instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422)",
			"/src/Foundation/NSUrlSessionHandler.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'SslProtocol.Tls_1_1' is obsoleted on: 'ios' 13.0 and later (Use 'TlsProtocolVersion' instead.), 'maccatalyst' 13.0 and later (Use 'TlsProtocolVersion' instead.), 'macOS/OSX' 10.15 and later (Use 'TlsProtocolVersion' instead.), 'tvos' 13.0 and later (Use 'TlsProtocolVersion' instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422)",
			"/src/Foundation/NSUrlSessionHandler.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'SslProtocol.Tls_1_2' is obsoleted on: 'ios' 13.0 and later (Use 'TlsProtocolVersion' instead.), 'maccatalyst' 13.0 and later (Use 'TlsProtocolVersion' instead.), 'macOS/OSX' 10.15 and later (Use 'TlsProtocolVersion' instead.), 'tvos' 13.0 and later (Use 'TlsProtocolVersion' instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422)",
			"/src/Foundation/NSUrlSessionHandler.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'SslProtocol.Tls_1_3' is obsoleted on: 'ios' 13.0 and later (Use 'TlsProtocolVersion' instead.), 'maccatalyst' 13.0 and later (Use 'TlsProtocolVersion' instead.), 'macOS/OSX' 10.15 and later (Use 'TlsProtocolVersion' instead.), 'tvos' 13.0 and later (Use 'TlsProtocolVersion' instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoder.GpuRegistryId' is supported on: 'ios' 13.0 and later, 'tvos' 13.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoder.IncludeStandardDefinitionDVEncoders' is supported on: 'ios' 15.0 and later, 'tvos' 15.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoder.InstanceLimit' is supported on: 'ios' 13.0 and later, 'tvos' 13.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoder.IsHardwareAccelerated' is supported on: 'ios' 13.0 and later, 'tvos' 13.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoder.PerformanceRating' is supported on: 'ios' 13.0 and later, 'tvos' 13.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoder.QualityRating' is supported on: 'ios' 13.0 and later, 'tvos' 13.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoder.SupportedSelectionProperties' is supported on: 'ios' 13.0 and later, 'tvos' 13.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoder.SupportsFrameReordering' is supported on: 'ios' 14.2 and later, 'tvos' 14.2 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoderList.GpuRegistryId.get' is supported on: 'ios' 13.0 and later, 'tvos' 13.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoderList.GpuRegistryId' is supported on: 'ios' 13.0 and later, 'tvos' 13.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoderList.IncludeStandardDefinitionDVEncoders.get' is supported on: 'ios' 15.0 and later, 'tvos' 15.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoderList.IncludeStandardDefinitionDVEncoders' is supported on: 'ios' 15.0 and later, 'tvos' 15.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoderList.InstanceLimit.get' is supported on: 'ios' 13.0 and later, 'tvos' 13.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoderList.InstanceLimit' is supported on: 'ios' 13.0 and later, 'tvos' 13.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoderList.IsHardwareAccelerated.get' is supported on: 'ios' 13.0 and later, 'tvos' 13.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoderList.IsHardwareAccelerated' is supported on: 'ios' 13.0 and later, 'tvos' 13.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoderList.PerformanceRating.get' is supported on: 'ios' 13.0 and later, 'tvos' 13.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoderList.PerformanceRating' is supported on: 'ios' 13.0 and later, 'tvos' 13.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoderList.QualityRating.get' is supported on: 'ios' 13.0 and later, 'tvos' 13.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoderList.QualityRating' is supported on: 'ios' 13.0 and later, 'tvos' 13.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoderList.SupportedSelectionProperties.get' is supported on: 'ios' 13.0 and later, 'tvos' 13.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoderList.SupportedSelectionProperties' is supported on: 'ios' 13.0 and later, 'tvos' 13.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoderList.SupportsFrameReordering.get' is supported on: 'ios' 14.2 and later, 'tvos' 14.2 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
			"/src/VideoToolbox/VTVideoEncoder.cs has 4 occurrences of This call site is reachable on: 'ios' 12.2 and later, 'maccatalyst' 12.2 and later, 'macOS/OSX' 12.0 and later, 'tvos' 12.2 and later. 'VTVideoEncoderList.SupportsFrameReordering' is supported on: 'ios' 14.2 and later, 'tvos' 14.2 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)",
		};
	}
}
